### PR TITLE
fix translation of aggregator

### PR DESCRIPTION
**Pull request by hms5232**
原本的翻譯是中國用語
臺灣的翻譯比較可能的是：聚集、彙總、整合
權衡後採用了聚集

------

如果這個 PR 有被接受且維護者願意的話，希望能幫我加上 `hacktoberfest-accepted` 幫助我參加活動，非常感謝！

### CODE REVIEW

**Review by weihanglo — COMMENTED** [review]
Could you provide some references for the suggestion? I feel like these terms aren't interchangeable between locale. "聚集" sounds more like gather/assemble to my instinct.

**Comment by hms5232** [comment]
> Could you provide some references for the suggestion? I feel like these terms aren't interchangeable between locale. "聚集" sounds more like gather/assemble to my instinct.

Sure, here is Microsoft office document page of `AGGREGATE()`: https://support.microsoft.com/zh-tw/office/aggregate-函數-43b9278e-6aa7-4f17-92b6-e19993fa26df

"彙總", "整合" and "聚集" can also seen in dictionary:

1. https://tw.dictionary.search.yahoo.com/search?p=aggregate
2. https://dictionary.cambridge.org/zht/詞典/英語-漢語-繁體/aggregate
3. https://dictionary.cambridge.org/zht/詞典/英語-漢語-繁體/aggregator

I think "聚集" is suitable for this context. What do you think?

**Review by weihanglo — APPROVED** [review]

**Comment by weihanglo** [comment]
Make sense. Thank you for the contribution!

@bors r+

**Comment by weihanglo** [comment]
I was thinking of RSS news aggregator, which can date back to 2009 Wikipedia: https://zh.m.wikipedia.org/w/index.php?title=%E8%81%9A%E5%90%88%E5%99%A8&oldid=10034636

**Comment by hms5232** [comment]
> I was thinking of RSS news aggregator, which can date back to 2009 Wikipedia: https://zh.m.wikipedia.org/w/index.php?title=%E8%81%9A%E5%90%88%E5%99%A8&oldid=10034636

I had seen this page when search "aggregator". It doesn't has "公共轉換" (sorry i can't find this word in English) and still show "聚合器" now. BTW, the ["公共轉換模組"](https://zh.wikipedia.org/zh-tw/Category:公共转换组模块) doesn't even apply 公共轉換模組🤪

For me, I will translate it to "RSS 新聞彙整器" in this case.

**Pull request merged**
